version: '2.3'
services:
    jupyter_notebook:
        build: ./deep_learning/
        #runtime: nvidia
        ports:
          - "8888:8888"
          - "5000:5000"
          - "1080:1080"
          - "10401:10401"
          - "10402:10402"
        expose:
            - "8888"
            - "27017"
            - "80"
            - "6379"
            - "8080"
            - "5000"
            - "1080"
            - "10401"
            - "10402"
        volumes:

            - /home/su/:/home/user/
            - /tmp/.X11-unix:/tmp/.X11-unix
            #xhost +local:docker in terminal before using
        #networks:
        #  application-network:
        #      aliases:
        #      - jupyter.compose
        restart: on-failure
        environment:
        - PYTHONUNBUFFERED=0
        - DISPLAY=unix:1
        #command : "jupyter notebook --no-browser --allow-root --ip=0.0.0.0 --port=8888"
        command : "python3 eu-ai-api/app.py"
#    mongo:
#        image: mongo
#        container_name: mongodb
#        command: mongod --port 10403
#        restart: always
#        volumes :
#       - /home/su/eu-ai-api/mongo_volume:/data/db
          #environment:
        #   MONGO_INITDB_ROOT_USERNAME: root
        #   MONGO_INITDB_ROOT_PASSWORD: example

    #mongo-express:
    #    image: mongo-express
    #    restart: always
    #    depends_on:
    #          - mongo
    #    ports: 
    #          - "10404:10404"
    #    expose:
    #          - "10404"
    #    environment:
    #       ME_CONFIG_MONGODB_SERVER: mongo
    #       ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #       ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #       ME_CONFIG_MONGODB_URL: mongo://root:example@mongo:10403/
#networks:
#    application-network:
#        external: true
